# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      aws:
        patterns:
          - github.com/aws/*
      es:
        patterns:
          - github.com/effective-security*
      go:
        patterns:
          - golang.org*
      google:
        patterns:
          - google.golang.org*
      k8s.io:
        patterns:
          - "*k8s.io/*"
  # Enable version updates for Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
