---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeca.fullname" $ }}-etc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeca.labels" $ | nindent 4 }}
data:
  {{- range $path, $_ :=  $.Files.Glob  "etc/*" }}
  {{ $path | base | replace "." "-" | replace "_" "-" }}: |-
{{ tpl ($.Files.Get $path) $ | indent 4 }}
  {{- end }}
