name: Build

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  context-info:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT" && \
          echo "GITHUB_REF=$GITHUB_REF GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME"
      - name: Repo info
        run: |
          curl -s \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}

  TestAndDeploy:
    runs-on: ubuntu-latest
    env:
      EVENT_NUMBER: ${{ github.event.number }}
    steps:
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.BUILDER_PAT }}
        run: git config --global url."https://dissoupov:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Prepare
        run: make vars tools folders generate  version change_log

      - name: UnitTest
        run: make build covtest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker kubeca meta
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: meta_kubeca
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            effectivesecurity/kubeca
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Docker kubeca docker_build_kubecertinit
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: docker_build_kubeca
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile.kubeca
          context: .
          push: true
          tags: ${{ steps.meta_kubeca.outputs.tags }}
          labels: ${{ steps.meta_kubeca.outputs.labels }}

      - name: Docker kubecertinit meta
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: meta_kubecertinit
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            effectivesecurity/kubecertinit
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Docker kubecertinit build
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: docker_build_kubecertinit
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile.kubecertinit
          context: .
          push: true
          tags: ${{ steps.meta_kubecertinit.outputs.tags }}
          labels: ${{ steps.meta_kubecertinit.outputs.labels }}

      - name: coveralls
        # if: github.event_name == 'pull_request'
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make coveralls-github
